### PR TITLE
Renamed Goods as PhysObj

### PR DESCRIPTION
**Pull request by gracinet**
After #16, if feels wrong to use "Goods" for the model representing all physical objects, since some of them are not goods at all (we could even have an Earth or Universe top location among them).

### CODE REVIEW

**Comment by petrus-v** [comment]
Sounds good to rename. I'm wondering how to manage virtual things likes licenses and so on but as long there is *no* physical things to represent virtual things I don't believes we needs to follow some stock ! 

I'm not so aware about all this folk works and have never played with it, I've only give a quick eye to the diff. I'm wondering:

- if you  plan to rename goods namespace en module to physobj as well (probably with some backward compatibility) ?
- I'm not sure if you make a difference between goods and physObj? does physObj supposed to support [GOODS_STATES](https://github.com/gracinet/anyblok_wms_base/blob/PhysObj/anyblok_wms_base/constants.py#L25) ?
- why Avatars still using "goods" m2o attributes (which is not renamed) ?

regards,

**Comment by gracinet** [comment]
I believe that all comments of @petrus-v are now addressed.
There would be new ones to add, such as the fields of Arrival and Apparition still been called `goods_type` etc, but I'm not sure if that's to be treated now.

I will indeed add migration steps to issue the relevant `ALTER TABLE` and `ALTER COLUMN` statements.

**Comment by gracinet** [comment]
Build fails because anyblok_wms_base requires a version of Anyblok that's not released yet.
We could switch Travis to GitHub's master branch of Anyblok if needed for the time of this PR (not worth the effort for now, and I think it has value to check on released versions).

**Comment by petrus-v** [comment]
Well done !

**Comment by gracinet** [comment]
thanks @petrus-v , lots of cherry picking and squashes in that one :-)

**Pull request merged**
